### GET
GET http://localhost:3001/blood-pressure-measurements
Accept: application/json

### POST
POST http://localhost:3001/blood-pressure-measurements
Content-Type: application/json

{
  "id": "be621291-3bf3-4808-87d1-7e93345c4c80",
  "systolicBloodPressure": 135,
  "diastolicBloodPressure": 95,
  "heartRate": 80,
  "date": "2026-09-02T00:00:00Z"
}

### PATCH
PATCH http://localhost:3001/blood-pressure-measurements/019d9a95-7c85-757c-96e7-d9b95104c0c1
Content-Type: application/json

{
  "systolicBloodPressure": 150,
  "diastolicBloodPressure":120,
  "heartRate":80
}

### DELETE
DELETE http://localhost:3001/blood-pressure-measurements/019d9a95-7c85-757c-96e7-d9b95104c0c1
Accept: application/json
