### GET
GET http://localhost:3001/todos/
Accept: application/json

### POST
POST http://localhost:3001/todos
Content-Type: application/json

{
  "id": "019f4631-26c5-7005-9ac2-0e743318ba18",
  "content": "Study SWR",
  "status": false,
  "date": "2026-07-09T09:24:14.150Z"
}

### PATCH
PATCH http://localhost:3001/todos/019f4631-26c5-7005-9ac2-0e743318ba18
Content-Type: application/json

{
  "status": true
}

### DELETE
DELETE http://localhost:3001/todos/019f4631-26c5-7005-9ac2-0e743318ba18
Accept: application/json
